# Ch1 NumPy的基礎

## 1-1 認識NumPy的基本操作

In [5]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3])

In [3]:
print(a * 3)
a + 2

[3 6 9]


array([3, 4, 5])

In [11]:
l = [1, 2, 3]
l * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [14]:
b = np.array([2, 2, 0])
print(a + b)
print(a / b)
print(a * b)

[3 4 3]
[0.5 1.  inf]
[2 4 0]


C:\Users\Vick\AppData\Local\Temp\ipykernel_24080\2732067425.py:3: RuntimeWarning: divide by zero encountered in divide
  print(a / b)


In [16]:
print(np.arange(10))
np.arange(0, 10, 2)

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8])

In [19]:
np.linspace(0, 10, 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [20]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
c.shape

(2, 3)

In [26]:
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], 
              [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [27]:
d.shape

(2, 4, 3)

In [33]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
c.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
c.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [41]:
import time

def calculate_time():
    a = np.random.randn(100000)
    b = list(a)
    start_time = time.time()
    for _ in range(1000):
        sum_1 = np.sum(a)
    print("Using NumPy\t %f sec" % (time.time() - start_time))
    start_time = time.time()
    for _ in range(1000):
        sum_2 = sum(b)
    print("Not using NumPy\t %f sec" % (time.time() - start_time))

calculate_time()

Using NumPy	 0.054142 sec
Not using NumPy	 7.073777 sec


## 1-2 ndarray陣列的基本概念

In [51]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))
print(a)
print(a.data)
print(a.dtype)
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.T)
b

<class 'numpy.ndarray'>
[1 2 3]
int32
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


array([[1, 2, 3],
       [4, 5, 6]])

## 1-3 ndarray的axis(軸)與dimension(維度)

In [45]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
print(a.ndim)

(2, 3)
2


In [54]:
a = np.array([[0, 1], [2, 3], [4, 5]])
print(a)
print(a.shape)
a.ndim

[[0 1]
 [2 3]
 [4 5]]
(3, 2)


2

In [56]:
b = np.array([a, a])
print(b.shape)
b

(2, 3, 2)


array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

In [57]:
b.sum(axis = 0)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [60]:
b.sum(axis = 1)

array([[6, 9],
       [6, 9]])

In [61]:
b.sum(axis = 2)

array([[1, 5, 9],
       [1, 5, 9]])

## 1-4 ndarray的dtype屬性

In [66]:
print(b.dtype)
b.dtype

int32


dtype('int32')

In [82]:
import numpy as np

a = np.array([0, 1, 2])
print(a.dtype) # 此台電腦預設是int32
b = np.array([0, 1, 2], dtype = "int64")
print(b.dtype)
b

int32
int64


array([0, 1, 2], dtype=int64)

In [92]:
c = np.array([0, 1, 2], dtype = "float64")
print(c)
# d = np.array([3e50, 4e30], dtype = "int64")
# print(d)
d = np.array([3e50, 4e35], dtype = "float")
print(d)
e = np.array([3.5, 4.2, -4.3], dtype = "int")
print(e)
f = np.array([0, 3, 0, -1], dtype = "bool")
f


[0. 1. 2.]
[3.e+50 4.e+35]
[ 3  4 -4]


array([False,  True, False,  True])

## 1-5 ndarray的切片（Slicing）操作

In [95]:
a = [1, 2, 3, 4, 5]
a[1: -1]

[2, 3, 4]

In [111]:
a = np.arange(10)
print(a)
print(a[1: 5])
print(a[2: 8: 2])
print(a[: : -1])
print(a[: 3])
print(a[4: ])
print(a[: 3], a[3: ]) # 沒有print的話，會變2個tuple
print(a[: : 2])
print(a[: ])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]
[2 4 6]
[9 8 7 6 5 4 3 2 1 0]
[0 1 2]
[4 5 6 7 8 9]
[0 1 2] [3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [120]:
b = np.arange(20).reshape(4, 5)
print(b)
b[1: 3, 2: 4]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 7,  8],
       [12, 13]])

In [125]:
print(b[: 2, 1: ])
print(b[: : 2, : ])
print(b[: , : : 2])
print(b[: , : : -1])
b[: : -1, : : -1]

[[1 2 3 4]
 [6 7 8 9]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## 1-6 陣列擴張（Broadcasting）

In [4]:
import numpy as np

a = np.array([[1, 2]])
print(a.shape)
b = np.array([3, 4])
print(b.shape)
a + b

(1, 2)
(2,)


array([[4, 6]])

In [6]:
a = np.array([1, 2])
b = np.array([[3, 4], [2, 3]])
print(a)
print(b)
print(a.shape)
print(b.shape)
a + b   

[1 2]
[[3 4]
 [2 3]]
(2,)
(2, 2)


array([[4, 6],
       [3, 5]])

In [12]:
a = np.arange(3)
print(a)
print(a.shape)
b = np.arange(6).reshape(3, 2)
print(b)
print(b.shape)
a + b

[0 1 2]
(3,)
[[0 1]
 [2 3]
 [4 5]]
(3, 2)


ValueError: operands could not be broadcast together with shapes (3,) (3,2) 