# Ch3 Numpy的數學函式

## 3-1 基本的數學運算函式

In [4]:
import numpy as np

a = np.array([0, 1, 2, 3, 4])
b = np.array([2, 4, 6, 8, 10])
print(a + b)
print(a + 4)
print(np.add(a, b))
print(np.add(a, 4))

[ 2  5  8 11 14]
[4 5 6 7 8]
[ 2  5  8 11 14]
[4 5 6 7 8]


In [9]:
print(a - b)
print(b - a)
print(a - 4)
print(np.subtract(a, b))
print(np.subtract(a, 4))

[-2 -3 -4 -5 -6]
[2 3 4 5 6]
[-4 -3 -2 -1  0]
[-2 -3 -4 -5 -6]
[-4 -3 -2 -1  0]


In [13]:
print(a * b)
print(a * 2)
print(np.multiply(a, b))
print(np.multiply(a, 2))

[ 0  4 12 24 40]
[0 2 4 6 8]
[ 0  4 12 24 40]
[0 2 4 6 8]


In [21]:
print(b / a)
print(b / 2)
print(b / 3)
print(np.divide(b, a))
print(np.divide(b, 2))
print(b // 3)
print(b % 3)
np.mod(b, 3)


[       inf 4.         3.         2.66666667 2.5       ]
[1. 2. 3. 4. 5.]
[0.66666667 1.33333333 2.         2.66666667 3.33333333]
[       inf 4.         3.         2.66666667 2.5       ]
[1. 2. 3. 4. 5.]
[0 1 2 2 3]
[2 1 0 2 1]


C:\Users\Vick\AppData\Local\Temp\ipykernel_64188\2602909602.py:1: RuntimeWarning: divide by zero encountered in divide
  print(b / a)
C:\Users\Vick\AppData\Local\Temp\ipykernel_64188\2602909602.py:4: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(b, a))


array([2, 1, 0, 2, 1], dtype=int32)

In [24]:
# numpy.floor_divide()函數進行整數除法。該函數將兩個數字進行除法運算，然後向下取整至最接近的整數。
import numpy as np

a = np.array([0, 1, 2, 3, 4])
b = np.array([2, 4, 6, 8, 10])

result = np.floor_divide(b, 3)
print(result)


[0 1 2 2 3]


In [30]:
print(np.power(2, 3))
print(2 ** 3)
a = np.arange(1, 11, 1)
b = np.array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])
print(a)
print(b)
print(np.power(a, b))
print(a ** b)
print(np.sqrt(2))
print(np.sqrt(a))

8
8
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 1 2 1 2 1 2 1 2]
[  1   4   3  16   5  36   7  64   9 100]
[  1   4   3  16   5  36   7  64   9 100]
1.4142135623730951
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [33]:
print(np.sin(0))
print(np.cos(0))
print(np.tan(0))
print(np.sin(np.pi * 0.5))
print(np.cos(np.pi * 0.5))
np.tan(np.pi * 0.5)

0.0
1.0
0.0
1.0
6.123233995736766e-17


1.633123935319537e+16

In [39]:
print(np.arcsin(0.5))
print(np.deg2rad(30))
print(np.arccos(0.5))
print(np.arctan(1.0))
print(np.arcsin(-1.0))
print(np.arccos(-1.0))
print(np.arctan(-0.5))
np.sin(0.5235987755982989)

0.5235987755982989
0.5235987755982988
1.0471975511965979
0.7853981633974483
-1.5707963267948966
3.141592653589793
-0.4636476090008061


0.5

In [38]:
print(np.deg2rad(120))
print(np.deg2rad(-90))
print(np.rad2deg(3.14))

2.0943951023931953
-1.5707963267948966
179.9087476710785


In [40]:
print(np.exp(1))
print(np.exp(2))
print(np.exp(0))

2.718281828459045
7.38905609893065
1.0


In [49]:
print(np.log(np.e))
a = np.array([1., 2., np.e ** 2, 10])
print(np.log(a))
b = np.array([1., 2., 4. ,7])
print(np.log2(b))
c = np.array([1., 10., 20., 100])
print(np.log10(c))
print(np.log(1 + 1))
print(np.log1p(0))
np.log1p(a)

1.0
[0.         0.69314718 2.         2.30258509]
[0.         1.         2.         2.80735492]
[0.      1.      1.30103 2.     ]
0.6931471805599453
0.0


array([0.69314718, 1.09861229, 2.12692801, 2.39789527])

In [50]:
print(np.log(2) / np.log(4))
print(np.log(9) / np.log(3))

0.5
2.0


In [58]:
print(np.sinh(2))
print((np.exp(2) - np.exp(-2)) / 2)
print(np.arcsinh(3.6268604078470186))
print(np.cosh(2))
print(np.tanh(2))
print(np.arccosh(1))
print(np.arctanh(0.7))

3.6268604078470186
3.626860407847019
2.0
3.7621956910836314
0.9640275800758169
0.0
0.8673005276940532


In [65]:
a = np.array([-1.8, -1.4, -1.0, -0.6, -0.2, 0., 0.2, 0.6, 1.0, 1.4, 1.8])
print(np.floor(a))
print(np.trunc(a))
print(np.ceil(a))
print(np.round(a))
print(np.around(a))
print(np.rint(a))
print(np.fix(a))

[-2. -2. -1. -1. -1.  0.  0.  0.  1.  1.  1.]
[-1. -1. -1. -0. -0.  0.  0.  0.  1.  1.  1.]
[-1. -1. -1. -0. -0.  0.  1.  1.  1.  2.  2.]
[-2. -1. -1. -1. -0.  0.  0.  1.  1.  1.  2.]
[-2. -1. -1. -1. -0.  0.  0.  1.  1.  1.  2.]
[-2. -1. -1. -1. -0.  0.  0.  1.  1.  1.  2.]
[-1. -1. -1. -0. -0.  0.  0.  0.  1.  1.  1.]


In [70]:
a = -2.5
print(np.absolute(a))
print(np.fabs(a))
b = -2 + 3j
print(np.abs(b))
# print(np.fabs(b))
c = np.array([-1, 2, -8, 12, 1 + 2j])
print(np.abs(c))

2.5
2.5
3.605551275463989
[ 1.          2.          8.         12.          2.23606798]


## 3-2 計算元素平均值-average()與mean()

In [1]:
import numpy as np

a = np.array([33, 44, 54, 23, 25, 55, 32, 76])
print(np.average(a))
a = a.reshape((2, 4))
print(a)
np.average(a)

42.75
[[33 44 54 23]
 [25 55 32 76]]


42.75

In [78]:
print(np.average(a, axis = 0))
print(np.average(a, axis = 1))
b = np.random.rand(24).reshape((2, 3, 4))
print(b)
print(np.average(b, axis = 0))
print(np.average(b, axis = 1))
np.average(b, axis = 2)

[29.  49.5 43.  49.5]
[38.5 47. ]
[[[0.99297612 0.22537309 0.39167115 0.76437156]
  [0.55498807 0.43548526 0.78709783 0.34595022]
  [0.71892233 0.87706978 0.44328259 0.09381974]]

 [[0.29538729 0.19863756 0.32532604 0.48385871]
  [0.03778575 0.42029579 0.360673   0.92339709]
  [0.12184673 0.97993335 0.37950688 0.51600108]]]
[[0.64418171 0.21200532 0.35849859 0.62411514]
 [0.29638691 0.42789052 0.57388541 0.63467366]
 [0.42038453 0.92850157 0.41139474 0.30491041]]
[[0.75562884 0.51264271 0.54068385 0.40138051]
 [0.15167326 0.53295556 0.35516864 0.64108563]]


array([[0.59359798, 0.53088035, 0.53327361],
       [0.3258024 , 0.43553791, 0.49932201]])

In [84]:
a = a.flatten()
w = np.array([0.1, 0.05, 0.2, 0.0, 0.0, 0.4, 0.2, 0.05])
print(np.average(a, weights = w))
w2 = np.array([0.2, 0.8])
a = a.reshape((2, 4))
print(a)
np.average(a, axis = 0, weights = w2)

48.5
[[33 44 54 23]
 [25 55 32 76]]


array([26.6, 52.8, 36.4, 65.4])

In [87]:
print(np.average(a, returned = True))
a = a.flatten()
print(a)
print(w)
np.average(a, weights = w, returned = True)

(42.75, 8.0)
[33 44 54 23 25 55 32 76]
[0.1  0.05 0.2  0.   0.   0.4  0.2  0.05]


(48.5, 1.0)

In [2]:
import numpy as np

np.random.seed(1)
a = np.random.randint(0, 10, 20)
print(a)
print(np.mean(a))
print(a.mean())
b = a.reshape((4, 5))
print(b)
print(np.mean(b))
print(b.mean())

[5 8 9 5 0 0 1 7 6 9 2 4 5 2 4 2 4 7 7 9]
4.8
4.8
[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]
 [2 4 7 7 9]]
4.8
4.8


In [9]:
print(np.mean(b, axis = 0))
print(np.mean(b, axis = 1))
c = np.random.rand(24).reshape((2, 3, 4))
print(c)
print(np.mean(c, axis = 0))
print(np.mean(c, axis = 1))
print(np.mean(c, axis = 2))

[2.25 4.25 7.   5.   5.5 ]
[5.4 4.6 3.4 5.8]
[[[0.28777534 0.13002857 0.01936696 0.67883553]
  [0.21162812 0.26554666 0.49157316 0.05336255]
  [0.57411761 0.14672857 0.58930554 0.69975836]]

 [[0.10233443 0.41405599 0.69440016 0.41417927]
  [0.04995346 0.53589641 0.66379465 0.51488911]
  [0.94459476 0.58655504 0.90340192 0.1374747 ]]]
[[0.19505488 0.27204228 0.35688356 0.5465074 ]
 [0.13079079 0.40072153 0.5776839  0.28412583]
 [0.75935618 0.36664181 0.74635373 0.41861653]]
[[0.35784035 0.18076794 0.36674855 0.47731881]
 [0.36562755 0.51216914 0.75386557 0.35551436]]
[[0.2790016  0.25552762 0.50247752]
 [0.40624246 0.44113341 0.6430066 ]]


In [15]:
print(b)
e = np.mean(b, keepdims = True)
print(e)
print(e.shape)
f = np.mean(b, keepdims = False)
print(f)
g = np.mean(b, axis = 1, keepdims = True)
print(g)
print(g.shape)
h = np.mean(b, axis = 1, keepdims = False)
print(h)
h.shape

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]
 [2 4 7 7 9]]
[[4.8]]
(1, 1)
4.8
[[5.4]
 [4.6]
 [3.4]
 [5.8]]
(4, 1)
[5.4 4.6 3.4 5.8]


(4,)

## 3-3 計算中位數-median()

In [3]:
import numpy as np

a = np.random.randint(100, size = (2, 3, 4))
print(a)
b = a.flatten()
b.sort()
print(b[11], b[12])
np.median(a)

[[[16  7 50 26]
  [32 42 48 77]
  [ 9 70 18 47]]

 [[45 51  5 29]
  [91 10 78 54]
  [84 74 43  4]]]
43 45


44.0

In [19]:
print(np.median(a, axis = 2))
print(np.median(a, axis = 1))

[[57.  72.5 38. ]
 [62.5 35.  88. ]]
[[76. 38. 43. 43.]
 [82. 69. 73. 26.]]


In [6]:
b = a.copy()
print(b)
print(np.median(b, axis = 1, overwrite_input = True))
print(np.all(a == b))
print(np.all(a == a))
print(a)
print(b)

[[[16  7 50 26]
  [32 42 48 77]
  [ 9 70 18 47]]

 [[45 51  5 29]
  [91 10 78 54]
  [84 74 43  4]]]
[[16. 42. 48. 47.]
 [84. 51. 43. 29.]]
False
True
[[[16  7 50 26]
  [32 42 48 77]
  [ 9 70 18 47]]

 [[45 51  5 29]
  [91 10 78 54]
  [84 74 43  4]]]
[[[ 9  7 18 26]
  [16 42 48 47]
  [32 70 50 77]]

 [[45 10  5  4]
  [84 51 43 29]
  [91 74 78 54]]]


In [26]:
b = a.copy()
%timeit np.median(a, axis = 1)
%timeit np.median(b, axis = 1, overwrite_input = True)

38.4 µs ± 933 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
34.2 µs ± 892 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [30]:
print(np.median(a, axis = 0, keepdims = True))
print(np.mean(a, axis = 0))
print(np.median(a, axis = 1, keepdims = False))
print(np.median(a, axis = 1, keepdims = True))

[[[63.5 78.  56.  47.5]
  [82.5 32.5 67.  35. ]
  [90.  63.5 69.5 26. ]]]
[[63.5 78.  56.  47.5]
 [82.5 32.5 67.  35. ]
 [90.  63.5 69.5 26. ]]
[[76. 38. 43. 43.]
 [82. 69. 73. 26.]]
[[[76. 38. 43. 43.]]

 [[82. 69. 73. 26.]]]


## 3-4 計算元素總和-sum()

In [10]:
import numpy as np

a = np.random.randint(0, 10, size = (2, 5))
print(a)
print(np.sum(a))
b = np.array([2, 4, 1, 6])
print(np.sum(b))
c = np.random.randint(0, 10, size = (2, 4, 5))
print(c)
np.sum(c)

[[0 1 8 4 3]
 [3 1 8 2 1]]
31
13
[[[6 4 8 8 3]
  [1 7 8 8 9]
  [3 2 5 6 3]
  [7 8 8 1 3]]

 [[9 7 2 9 5]
  [8 2 7 6 0]
  [0 8 2 3 7]
  [2 0 0 6 6]]]


197

In [18]:
print(a)
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))
print(c)
print(np.sum(c, axis = 0))
print(np.sum(c, axis = 1))
print(np.sum(c, axis = 2))

[[0 1 8 4 3]
 [3 1 8 2 1]]
[ 3  2 16  6  4]
[16 15]
[[[6 4 8 8 3]
  [1 7 8 8 9]
  [3 2 5 6 3]
  [7 8 8 1 3]]

 [[9 7 2 9 5]
  [8 2 7 6 0]
  [0 8 2 3 7]
  [2 0 0 6 6]]]
[[15 11 10 17  8]
 [ 9  9 15 14  9]
 [ 3 10  7  9 10]
 [ 9  8  8  7  9]]
[[17 21 29 23 18]
 [19 17 11 24 18]]
[[29 33 19 27]
 [32 23 20 14]]


In [21]:
print(np.sum(c, axis = 0, keepdims = True))
print(np.sum(c, axis = 1, keepdims = True))
np.sum(c, axis = 2, keepdims = True)

[[[15 11 10 17  8]
  [ 9  9 15 14  9]
  [ 3 10  7  9 10]
  [ 9  8  8  7  9]]]
[[[17 21 29 23 18]]

 [[19 17 11 24 18]]]


array([[[29],
        [33],
        [19],
        [27]],

       [[32],
        [23],
        [20],
        [14]]])

## 3-5 計算標準差-std()

In [32]:
import numpy as np

print(np.std([10, 6440, 99999])) # 可以用()取代[]
print(np.std([99999, 99998, 99970]))

45695.16325243479
13.4412301024373


In [22]:
import numpy as np

a = np.random.rand(10)
print(a)
np.std(a)

[0.74941111 0.61172255 0.87142807 0.09753265 0.98000602 0.79797441
 0.90009354 0.7355938  0.32395146 0.51340009]


0.2627890798981281

In [25]:
b = np.random.rand(2, 3, 4)
print(b)
print(np.std(b, axis = 0))
np.std([b[0][0][0], b[1][0][0]])

[[[0.67201297 0.82617263 0.64713289 0.10424272]
  [0.72787859 0.40598977 0.84691874 0.4863432 ]
  [0.80998006 0.89804402 0.52186912 0.05369402]]

 [[0.41584835 0.99454696 0.35442087 0.30495184]
  [0.79241042 0.03034979 0.39688563 0.36425235]
  [0.28769544 0.96224166 0.02153898 0.87496719]]]
[[0.12808231 0.08418717 0.14635601 0.10035456]
 [0.03226591 0.18781999 0.22501656 0.06104542]
 [0.26114231 0.03209882 0.25016507 0.41063659]]


0.1280823071377552

In [29]:
print(np.std(b))
print(np.std(b, ddof = 1))

0.30258279934246063
0.3090907008426403


## 3-6 計算變異數-var()

In [30]:
import numpy as np

a = np.array([10, 20, 12, 0, 3, 5])
np.var(a)

43.55555555555555

## 3-7 計算共變異數-cov()

In [39]:
a = np.array([[10, 5, 2, 4, 9, 3, 2], 
              [10, 2, 8, 3, 7, 4, 1]])
print(np.cov(a))
print(np.var(a[0], ddof = 1))
print(np.var(a[1], ddof = 1))
c = np.array([3, 2, 1, 5, 7, 2, 1])
print(np.cov(a, c))
print(np.var(c, ddof = 1))

[[10.66666667  6.66666667]
 [ 6.66666667 11.33333333]]
10.666666666666666
11.333333333333334
[[10.66666667  6.66666667  4.66666667]
 [ 6.66666667 11.33333333  1.66666667]
 [ 4.66666667  1.66666667  5.        ]]
5.0


In [44]:
import pandas as pd

df = pd.DataFrame(np.vstack((a, c))).T
df.corr()

0         1         2
0  1.000000  0.606339  0.639010
1  0.606339  1.000000  0.221404
2  0.639010  0.221404  1.000000

In [49]:
print(np.cov(a, bias = False))
print(np.cov(a, bias = True))
print(np.var(a[0]))
print(np.var(a[1]))

[[10.66666667  6.66666667]
 [ 6.66666667 11.33333333]]
[[9.14285714 5.71428571]
 [5.71428571 9.71428571]]
9.142857142857142
9.714285714285714


In [52]:
print(np.cov(a, ddof = None))
print(np.cov(a, ddof = 1))
print(np.cov(a, ddof = 0))

[[10.66666667  6.66666667]
 [ 6.66666667 11.33333333]]
[[10.66666667  6.66666667]
 [ 6.66666667 11.33333333]]
[[9.14285714 5.71428571]
 [5.71428571 9.71428571]]


In [54]:
print(a)
fweights = np.array([1, 2, 2, 1, 1, 1, 1])
np.cov(a, fweights = fweights)

[[10  5  2  4  9  3  2]
 [10  2  8  3  7  4  1]]


array([[ 9.   ,  3.875],
       [ 3.875, 10.75 ]])

In [60]:
aweights = np.array([0.1, 0.2, 0.2, 0.2, 0.1, 0.1, 0.1])
print(np.cov(a, aweights = None))
print(np.cov(a, aweights = aweights))

[[10.66666667  6.66666667]
 [ 6.66666667 11.33333333]]
[[ 8.61904762  3.83333333]
 [ 3.83333333 10.66666667]]


## 3-8 計算相關係數-corrcoef()

In [61]:
import numpy as np

x = np.array([
    [1, 2, 1, 9, 10, 3, 2, 6, 7], 
    [2, 1, 8, 3, 7, 5, 10, 7, 2]
])
np.corrcoef(x)

array([[ 1.        , -0.05640533],
       [-0.05640533,  1.        ]])

In [62]:
y = np.array([2, 1, 1, 8, 9, 4, 3, 5, 7])
np.corrcoef(x, y)

array([[ 1.        , -0.05640533,  0.97094584],
       [-0.05640533,  1.        , -0.01315587],
       [ 0.97094584, -0.01315587,  1.        ]])

In [69]:
print(np.corrcoef(x, rowvar = False))
x_transpose = x.T
# x_transpose
print(np.corrcoef(x_transpose, rowvar = False))
np.corrcoef(x_transpose, rowvar = True) # 等於不設rowvar

[[ 1. -1.  1. -1. -1.  1.  1.  1. -1.]
 [-1.  1. -1.  1.  1. -1. -1. -1.  1.]
 [ 1. -1.  1. -1. -1.  1.  1.  1. -1.]
 [-1.  1. -1.  1.  1. -1. -1. -1.  1.]
 [-1.  1. -1.  1.  1. -1. -1. -1.  1.]
 [ 1. -1.  1. -1. -1.  1.  1.  1. -1.]
 [ 1. -1.  1. -1. -1.  1.  1.  1. -1.]
 [ 1. -1.  1. -1. -1.  1.  1.  1. -1.]
 [-1.  1. -1.  1.  1. -1. -1. -1.  1.]]
[[ 1.         -0.05640533]
 [-0.05640533  1.        ]]


array([[ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.]])

## 3-9 網格陣列-meshgrid()

In [71]:
import numpy as np

a = np.array([0, 1, 2])
b = np.array([4, 0])
aa, bb = np.meshgrid(a, b)
print(aa)
print(bb)

[[0 1 2]
 [0 1 2]]
[[4 4 4]
 [0 0 0]]


In [80]:
aa2, bb2 = np.meshgrid(a, b, indexing = "xy")
print(aa2)
print(bb2)
aa3, bb3 = np.meshgrid(a, b, indexing = "ij")
print(aa3)
print(bb3)

[[0 1 2]
 [0 1 2]]
[[4 4 4]
 [0 0 0]]
[[0 0]
 [1 1]
 [2 2]]


array([[4, 0],
       [4, 0],
       [4, 0]])

In [79]:
av, bv = np.meshgrid(a, b, sparse = True)
print(av)
print(bv)

[[0 1 2]]
[[4]
 [0]]


## 3-10 點積運算-dot()

In [83]:
import numpy as np

a = np.array([1, 2])
b = np.array([4, 3])
print(np.dot(a, b))
print(np.dot(4, 5))

10
20


In [88]:
e = np.matrix([1, 2])
f = np.matrix([4, 3])
print(f)
# print(np.dot(e, f))
f = np.matrix([[4], [3]])
print(f)
np.dot(e, f)


[[4 3]]
[[4]
 [3]]


matrix([[10]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])
np.dot(a, b)

In [89]:
print(np.dot(b, a))
c = np.arange(9).reshape((3, 3))
d = np.ones((3, 3))
np.dot(c, d)

10


array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [91]:
a = np.arange(12).reshape((4, 3))
b = np.arange(16).reshape((4, 4))
# np.dot(a, b)

In [92]:
e = np.matrix([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
f = np.matrix([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
np.dot(e, f)

matrix([[ 3,  3,  3],
        [12, 12, 12],
        [21, 21, 21]])

## 3-11 計算矩陣的determinant-linalg.det()

In [98]:
import numpy as np
import numpy.linalg as LA

a = np.array([[2, 3], [4, -1]])
print(a)
print(LA.det(a))
d = np.random.randint(-5, 6, size = (3, 3, 3))
print(d)
LA.det(d)

[[ 2  3]
 [ 4 -1]]
-14.000000000000004
[[[ 1 -5 -2]
  [-3 -3 -2]
  [-1 -4  0]]

 [[-5 -3  3]
  [ 1  4 -4]
  [-2  5  1]]

 [[ 4 -5 -3]
  [-5  1 -3]
  [ 0 -3  2]]]


array([ -36., -102., -123.])

## 3-12 計算矩陣的「特徵值」與「特徵向量」-linalg.eig()

In [4]:
import numpy as np
import numpy.linalg as LA

a = np.array([[1, 0], [0, 2]])
print(a)
print(LA.eig(a))
b = np.array([[2, 5], [3, -8]])
print(b)
LA.eig(b)

[[1 0]
 [0 2]]
(array([1., 2.]), array([[1., 0.],
       [0., 1.]]))
[[ 2  5]
 [ 3 -8]]


(array([ 3.32455532, -9.32455532]),
 array([[ 0.96665615, -0.40390206],
        [ 0.25607791,  0.91480224]]))

In [9]:
c = np.random.randint(-10, 10, size = (3, 3))
w, v = LA.eig(c)
print(w)
v

[ 5.82642252+4.02867447j  5.82642252-4.02867447j -7.65284504+0.j        ]


array([[-0.41949945+0.55137973j, -0.41949945-0.55137973j,
        -0.39580644+0.j        ],
       [-0.0132865 -0.07588604j, -0.0132865 +0.07588604j,
         0.74877344+0.j        ],
       [ 0.71698354+0.j        ,  0.71698354-0.j        ,
         0.53167246+0.j        ]])

In [12]:
c = np.random.randint(-10, 10, size = (3, 3, 3))
print(c)
w, v = LA.eig(c)
print(w)
v

[[[  5   6   0]
  [  5   9  -3]
  [ -4   2 -10]]

 [[  9   7   5]
  [  8   5  -8]
  [ -4  -3  -1]]

 [[  7  -4  -7]
  [ -6   4  -4]
  [ -2   4  -6]]]
[[12.92178293+0.j          0.39855401+0.j         -9.32033694+0.j        ]
 [14.93700493+0.j          0.03396691+0.j         -1.97097184+0.j        ]
 [11.49266477+0.j         -3.24633239+2.01973903j -3.24633239-2.01973903j]]


array([[[-0.60338463+0.j        , -0.73100782+0.j        ,
         -0.07595697+0.j        ],
        [-0.79664701+0.j        ,  0.5606155 +0.j        ,
          0.18128824+0.j        ],
        [ 0.0357845 +0.j        ,  0.38902162+0.j        ,
          0.98049228+0.j        ]],

       [[-0.61614407+0.j        , -0.58412719+0.j        ,
         -0.574633  +0.j        ],
        [-0.73137898+0.j        ,  0.80741536+0.j        ,
          0.80809744+0.j        ],
        [ 0.2923205 +0.j        , -0.08292076+0.j        ,
          0.12952007+0.j        ]],

       [[-0.81516577+0.j        , -0.55372494+0.06213923j,
         -0.55372494-0.06213923j],
        [ 0.5374107 +0.j        , -0.68114627+0.j        ,
         -0.68114627-0.j        ],
        [ 0.21608911+0.j        , -0.40336566+0.25072558j,
         -0.40336566-0.25072558j]]])

## 3-13 計算矩陣的rank-linalg.matrix_rank()

In [15]:
import numpy as np

A = np.array([[1, 1, 4, 0, 1], 
              [0, 3, 1, 3, 2], 
              [1, 3, 0, 0, 1], 
              [2, 4, 3, 1, 1]])
print(np.linalg.matrix_rank(A))
B = np.array([[1, 2, 3, 0], 
              [2, 4, 6, 0], 
              [1, 0, 1, 2], 
              [1, 0, 0, 3]])
print(np.linalg.matrix_rank(B))
C = np.array([[1, 2, 3, 0], 
              [2, 4, 7, 0], 
              [1, 0, 1, 2], 
              [1, 0, 0, 3]])
np.linalg.matrix_rank(C)

4
3


4

## 3-14 計算矩陣的「反矩陣」-linalg.inv()

In [6]:
import numpy as np

a = np.random.randint(-9, 10, size = (2, 2))
print(a)
print(np.linalg.inv(a))
print(np.dot(a, np.linalg.inv(a)))

[[-9  5]
 [-6 -3]]
[[-0.05263158 -0.0877193 ]
 [ 0.10526316 -0.15789474]]
[[1.00000000e+00 0.00000000e+00]
 [5.55111512e-17 1.00000000e+00]]


In [9]:
b = np.random.randint(-10, 10, size = (3, 3))
print(b)
c = np.linalg.inv(b)
print(c)
np.dot(b, c)

[[-3  2 -7]
 [-4  4 -2]
 [-1 -5  9]]
[[-0.15294118 -0.1        -0.14117647]
 [-0.22352941  0.2        -0.12941176]
 [-0.14117647  0.1         0.02352941]]


array([[ 1.00000000e+00, -1.11022302e-16, -2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00, -2.22044605e-16,  1.00000000e+00]])

In [12]:
d = [[1, 4, 3], 
     [-1, -3, 0], 
     [2, 4, 3]]
print(d)
print(np.linalg.inv(d))
print(2 / 9, 4 / 9, 1 / 9)

[[1, 4, 3], [-1, -3, 0], [2, 4, 3]]
[[-1.          0.          1.        ]
 [ 0.33333333 -0.33333333 -0.33333333]
 [ 0.22222222  0.44444444  0.11111111]]
0.2222222222222222 0.4444444444444444 0.1111111111111111


## 3-15 計算張量積-outer()

In [4]:
import numpy as np

a = np.array([1, 2, 3, 2, 1])
b = np.array([0, 2, 4, 6, 8, 1])

print(a.shape)
print(b.shape)
print(np.outer(a, b))

(5,)
(6,)
[[ 0  2  4  6  8  1]
 [ 0  4  8 12 16  2]
 [ 0  6 12 18 24  3]
 [ 0  4  8 12 16  2]
 [ 0  2  4  6  8  1]]


In [12]:
b = b.reshape((2, -1))
print(b)
c = np.random.randint(0, 5, size = (2, 4))
print(c)
print(np.outer(b, c))
np.outer(b.ravel(), c.ravel())

[[0 2 4]
 [6 8 1]]
[[2 3 2 0]
 [1 3 1 2]]
[[ 0  0  0  0  0  0  0  0]
 [ 4  6  4  0  2  6  2  4]
 [ 8 12  8  0  4 12  4  8]
 [12 18 12  0  6 18  6 12]
 [16 24 16  0  8 24  8 16]
 [ 2  3  2  0  1  3  1  2]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  6,  4,  0,  2,  6,  2,  4],
       [ 8, 12,  8,  0,  4, 12,  4,  8],
       [12, 18, 12,  0,  6, 18,  6, 12],
       [16, 24, 16,  0,  8, 24,  8, 16],
       [ 2,  3,  2,  0,  1,  3,  1,  2]])

## 3-16 計算叉積-cross()

In [26]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([5, 4, 0])
print(np.cross(a, b))
c = np.array([-1, 1, 3])
d = np.array([2, 3, 3])
np.cross(c, d)

[-12  15  -6]


array([-6,  9, -5])

In [15]:
b_2 = np.array([5, 4])
np.cross(a, b_2)

array([-12,  15,  -6])

In [17]:
ac = np.vstack((a, c))
bd = np.vstack((b, d))
print(ac)
print(bd)
print(np.cross(ac, bd))

[[ 1  2  3]
 [-1  1  3]]
[[5 4 0]
 [2 3 3]]
[[-12  15  -6]
 [ -6   9  -5]]


In [21]:
ac_2 = ac.transpose()
print(ac_2)
# np.cross(ac_2, bd) Mismatch is between arg 0 with shape (3,) and arg 1 with shape (2,).

[[ 1 -1]
 [ 2  1]
 [ 3  3]]


In [27]:
np.cross(ac_2, bd, axisa = 0)

array([[-12,  15,  -6],
       [ -6,   9,  -5]])

In [30]:
bd_2 = bd.transpose() # np.transpose(bd)也可以
print(bd_2)
np.cross(ac, bd_2, axisb = 0)

[[5 2]
 [4 3]
 [0 3]]


array([[-12,  15,  -6],
       [ -6,   9,  -5]])

In [32]:
print(np.cross(ac, bd, axisc = 1))
print(np.cross(ac, bd, axisc = 0))

[[-12  15  -6]
 [ -6   9  -5]]
[[-12  -6]
 [ 15   9]
 [ -6  -5]]


In [35]:
print(np.cross(ac_2, bd_2, axis = 0))

[[-12  -6]
 [ 15   9]
 [ -6  -5]]


In [40]:
# print(np.cross(np.array([1, 1, 1, 1]), np.array([1, 1, 1, 1])))
# print(np.cross(np.array([1]), np.array([1])))

## 3-17 計算卷積-convolve()

In [49]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])
v = np.array([0.2, 0.8])
print(np.convolve(a, v))
print(np.convolve(a, v, mode = "full"))
print(np.convolve(a, v, mode = "same"))
print(np.convolve(a, v, mode = "valid"))

[0.  0.2 1.2 2.2 3.2 4.2 4. ]
[0.  0.2 1.2 2.2 3.2 4.2 4. ]
[0.  0.2 1.2 2.2 3.2 4.2]
[0.2 1.2 2.2 3.2 4.2]


## 3-18 將數值劃分為不同區間-digitize()

In [51]:
import numpy as np

print(np.digitize(1, [0, 1]))
print(np.digitize(1, [0, 1], right = True))

2
1


In [52]:
for i in range(10):
    print(np.digitize(i, bins = [0, 4, 7]))

1
1
1
1
2
2
2
3
3
3
